import { writeFile } from 'node:fs/promises';
import { bankingDemoProfile } from '../src/data/banking-demo';

// Generate reproducible SQL from the same normalized provider fixture.
const events = bankingDemoProfile().transactions;
const json = ('[\n'+events.map(event=>JSON.stringify(event)).join(',\n')+'\n]').replaceAll("'", "''");
const sql = `-- Generated by npm run demo:seed-sql from src/data/banking-demo.ts.
-- Updates only the deterministic demo event IDs; preserves unrelated rows.
INSERT INTO public.financial_events(time,user_id,event_id,amount_cents,category,merchant,event_type,account_id)
SELECT x."timestamp"::timestamptz,x."userId",x.id,x."amountCents",x.category,x.merchant,x."eventType",x."accountId"
FROM jsonb_to_recordset('${json}'::jsonb) AS x("timestamp" text,"userId" text,id text,"amountCents" bigint,category text,merchant text,"eventType" text,"accountId" text)
ON CONFLICT(user_id,event_id,time) DO UPDATE SET amount_cents=EXCLUDED.amount_cents,category=EXCLUDED.category,merchant=EXCLUDED.merchant,event_type=EXCLUDED.event_type,account_id=EXCLUDED.account_id;
CALL refresh_continuous_aggregate('public.daily_spending',TIMESTAMPTZ '2026-07-14 00:00+00',TIMESTAMPTZ '2026-09-12 00:00+00');
CALL refresh_continuous_aggregate('public.daily_cash_flow',TIMESTAMPTZ '2026-07-14 00:00+00',TIMESTAMPTZ '2026-09-12 00:00+00');
`;
void writeFile('database/seed.sql',sql);
