"""Expo setup UI regressions. Backend unavailable by design; forecasts use the real demo engine."""
import os,json
from auth_fixture import authenticated_fixture
from playwright.sync_api import sync_playwright,expect
base=os.environ.get('MOBILE_PREVIEW_URL','http://127.0.0.1:8084')
with sync_playwright() as p:
    browser=p.chromium.launch(channel='chrome',headless=True)
    page=browser.new_page(viewport={'width':390,'height':844})
    errors=[]; requests=[]
    authenticated_fixture(page)
    page.on('pageerror',lambda error:errors.append(str(error)))
    def unavailable(route):
        if route.request.post_data: requests.append(json.loads(route.request.post_data))
        route.fulfill(status=503,content_type='application/json',headers={'Access-Control-Allow-Origin':base,'Access-Control-Allow-Credentials':'true'},body='{}')
    page.route('**/api/analyze',unavailable)
    page.goto(base,wait_until='networkidle')
    page.get_by_role('button',name='Financial setup',exact=True).click()
    page.get_by_role('textbox',name='Safety buffer · USD',exact=True).fill('500.01')
    page.get_by_role('button',name='Add bill',exact=True).click()
    page.get_by_role('textbox',name='Name',exact=True).fill('Test phone bill')
    page.get_by_role('textbox',name='Amount · USD',exact=True).fill('65.12')
    page.get_by_role('textbox',name='Date · YYYY-MM-DD',exact=True).fill('2026-02-30')
    page.get_by_role('button',name='Apply entry',exact=True).click()
    expect(page.get_by_role('alert')).to_be_visible()
    page.get_by_role('textbox',name='Date · YYYY-MM-DD',exact=True).fill('2026-09-20')
    page.get_by_role('button',name='monthly',exact=True).click()
    page.get_by_role('button',name='Apply entry',exact=True).click()
    expect(page.get_by_role('button',name='Edit bill: Test phone bill',exact=True)).to_be_visible()
    page.get_by_role('button',name='Add income',exact=True).click()
    page.get_by_role('textbox',name='Name',exact=True).fill('Weekend work')
    page.get_by_role('textbox',name='Amount · USD',exact=True).fill('200.25')
    page.get_by_role('textbox',name='Date · YYYY-MM-DD',exact=True).fill('2026-09-19')
    page.get_by_role('button',name='Apply entry',exact=True).click()
    page.get_by_role('button',name='Add goal',exact=True).click()
    page.get_by_role('textbox',name='Name',exact=True).fill('New laptop')
    page.get_by_role('textbox',name='Target · USD',exact=True).fill('1000')
    page.get_by_role('textbox',name='Deadline · YYYY-MM-DD (optional)',exact=True).fill('2026-11-01')
    page.get_by_role('textbox',name='Allowed delay · days',exact=True).fill('7')
    page.get_by_role('button',name='Apply entry',exact=True).click()
    page.get_by_role('button',name='Prioritize: New laptop',exact=True).click()
    expect(page.get_by_role('button',name='Prioritize: New laptop',exact=True)).to_be_disabled()
    page.get_by_role('button',name='Save setup & update forecast',exact=True).click()
    expect(page.get_by_text('Setup saved. Your purchase result, Safe Date, and goal impacts are updated.',exact=True)).to_be_visible()
    page.screenshot(path='/tmp/canibuyit-settings.png',full_page=True)
    page.goto(base,wait_until='networkidle')
    page.get_by_role('button',name='Financial setup',exact=True).click()
    expect(page.get_by_role('textbox',name='Safety buffer · USD',exact=True)).to_have_value('500.01')
    expect(page.get_by_role('button',name='Edit bill: Test phone bill',exact=True)).to_be_visible()
    expect(page.get_by_role('button',name='Edit income: Weekend work',exact=True)).to_be_visible()
    expect(page.get_by_role('button',name='Prioritize: New laptop',exact=True)).to_be_disabled()
    page.get_by_role('button',name='Edit bill: Test phone bill',exact=True).click()
    expect(page.get_by_role('textbox',name='Amount · USD',exact=True)).to_have_value('65.12')
    page.get_by_role('button',name='Cancel edit',exact=True).click()
    page.get_by_role('button',name='Remove bill: Test phone bill',exact=True).click()
    page.get_by_role('button',name='Save setup & update forecast',exact=True).click()
    expect(page.get_by_text('Setup saved. Your purchase result, Safe Date, and goal impacts are updated.',exact=True)).to_be_visible()
    page.go_back()
    page.get_by_role('button',name='Refresh finances',exact=True).click()
    expect(page.get_by_text('Couldn’t refresh. Your last result is still available.',exact=True)).to_be_visible()
    assert requests[-1]['settings']['safetyBufferCents']==50001
    assert requests[-1]['settings']['goals'][0]['name']=='New laptop'
    page.get_by_role('button',name='Check Purchase',exact=True).click()
    page.get_by_role('button',name='Use sample finances',exact=True).click()
    expect(page.get_by_text('$500.01',exact=True).first).to_be_visible()
    expect(page.get_by_text('Why wait?',exact=True)).to_be_visible()
    for width in [320,390,768]:
        page.set_viewport_size({'width':width,'height':844})
        assert page.evaluate('document.documentElement.scrollWidth <= innerWidth'),f'Overflow at {width}'
    assert not errors,errors
    print('PASS: setup validation, cents, recurring bills, income, goal deadline and priority, edits/removal, persistence, failed refresh preservation, configured purchase result and responsive layout.')
    browser.close()
